vcs:
    git:
    - url: https://github.com/triologygmbh/dependency-check
steps:
  execute:
  - mvn : 1.9.3
    goals: 'install'
    concurrent: true
  - mvn : 1.9.3
    goals: 'org.owasp:dependency-check-maven:check'
    concurrent: true