vcs:
    git:
    - url: https://github.com/eiselems/spring-boot-microservices
steps:
  execute:
  - mvn : 1.9.3
    goals: 'validate'
    concurrent: false
  - mvn : 1.9.3
    goals: 'install'
    concurrent: false
  - mvn : 1.9.3
    goals: 'test'
    concurrent: false