vcs:
    git:
    - url: https://github.com/spring-projects/spring-petclinic
steps:
  execute:
  - mvn : 1.9.3
    goals: 'validate'
    concurrent: false
  - mvn : 1.9.3
    goals: 'test'
    concurrent: false